core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . forms import LoginForm

from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('hotels/', views.hotels, name="hotels"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
]

invitations/urls.py
from django.urls import path

from . import views

app_name="invitations"

urlpatterns = [
    path('', views.index, name="index"),
    path('/banners/', views.banners, name="banners"),
]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('invitations', include('invitations.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.
class RegisterModel(models.Model):

    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.CharField(max_length=100, unique=True)
    number = models.IntegerField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

invitations/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from . models import RegisterModel

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'   
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder':'Your username', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder':'Your email', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

class RegisterForm(forms.ModelForm):
    class Meta:
        model = RegisterModel
        fields = ('name', 'surname', 'email', 'number', 'status')

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First Name',
        'class': 'w-full text-black py-2 px-4 rounded-xl'
    }), label=False)

    surname = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Mbiemer',
        'class': 'w-full text-black py-2 px-4 rounded-xl'
    }), label=False)

    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full text-black py-2 px-4 rounded-xl'
    }), label=False)

    number = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder': 'Num',
        'class': 'w-full text-black py-2 px-4 rounded-xl'
    }), label=False)

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import RegisterForm
from . forms import SignupForm

# Create your views here.
def signup(request):

	if request.method == "POST":
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form,
	})

def index(request):
    if request.method == "POST":
        form =  RegisterForm(request.POST)

        if form.is_valid():
            subscription = form.save(commit=False)
            subscription.save()
            return redirect('core:index') 
    else:
        form = RegisterForm()

    return render(request, "core/index.html", {
        "form": form,
    })

def hotels(request):
    return render(request, "core/hotels.html")

invitations/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "invitations/index.html")

def banners(request):
    return render(request, "invitations/banners.html")

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Puddle | Main{% endblock %}

{% block content %}
    <div class="flex flex-col mb-4">
        <div id="movingElementExample" class="flex flex-col justify-center items-center">
            <h1 class="text-6xl text-white font-bold mb-4 max-[376px]:text-2xl">THANK YOU, MIAMI!</h1>
            <h1 class="mb-4 text-3xl text-white font-bold max-[768px]:mb-4 max-[376px]:text-xl">SEE YOU AGAIN</h1>
            <img src="https://images.squarespace-cdn.com/content/v1/56bbcc4659827e5156d54504/feee5a20-eea2-4ba2-899a-ea0068128b2d/LeanneLeuterio-%40Snap_LL-TravisScott-8851.jpg?format=1500w" class="w-3/4" alt="Concert image"/>
        </div>
        <div class="my-4 mb-12">
            <form method="POST" action=".">
                {% csrf_token %}

                <div class="flex justify-center">
                    <div class="mx-auto w-3/4 my-4">
                        <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
                            <div>
                                {{ form.name }}
                            </div>
                            <div>
                                {{ form.surname }}
                            </div>
                            <div>
                                {{ form.email }}
                            </div>
                            <div>
                                {{ form.number }}
                            </div>
                        </div>
                        <div class="my-4">
                            {{ form.status }} <p class="text-white font-normal text-lg max-[426px]:text-sm">Id like to receive by e-mail and SMS the latest information on Rolling Loud products, sweepstakes, events, and more.</p>
                        </div>
                    </div>
                </div>

                <div class="flex justify-center mt-8">
                    <button class="text-md font-light px-6 py-2 text-white bg-transparent outline-none border border-2 border-white border-solid transition-all duration-300 ease-in-out hover:bg-white hover:text-black">SUBSCRIBE</button>
                </div>
            </form>
        </div>
        <div class="mt-12 text-white my-4 border-t-2 border-slate-900">
            <div class="flex flex-col justify-center items-center p-8 mt-8">
                <h1 class="text-center tracking-wide text-6xl font-bold mb-6 max-[768px]:text-4xl max-[426px]:text-3xl">VIP TICKETS FOR LIFE!</h1>
                <p class="mb-6 max-[768px]:text-sm max-[768px]:w-3/4">Introducing our genesis NFT project LoudPunx which will give you access to all Rolling Loud’s for LIFE plus so much more.</p>
                <p class="font-bold text-md">VERIFIED ON OPENSEA ✅</p>
                <img class="mt-6 w-3/4 max-[426px]:w-full" src="https://images.squarespace-cdn.com/content/v1/56bbcc4659827e5156d54504/cf1404fe-b950-4353-a789-8cdd209acac4/loudpunx+banner.jpg?format=1500w" />
            </div>
            <div class="mt-4 flex flex-row justify-around items-center text-lg max-[426px]:flex-col">
                <button class="px-8 py-4 font-normal text-black bg-white outline-none border-none transition-all duration-300 ease-in-out hover:bg-gray-400 max-[426px]:mb-8">HELLO</button>
                <button class="px-8 py-4 font-normal text-black bg-white outline-none border-none transition-all duration-300 ease-in-out hover:bg-gray-400">WORLD</button>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="w-1/2 p-6 mx-auto my-6 bg-black text-white rounded-xl">
		<h1 class="mb-6 text-3xl font-semibold">Log in</h1>

		<form method="post" action=".">
			{% csrf_token %}

			<div class="mb-3">
				<label class="inline-block mb-2">Username</label><br>
				{{ form.username }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Password</label><br>
				{{ form.password }}
			</div>

			{% if form.errors or form.non_field_errors %}
				<div class="mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %} 
						{{ field.errors }}
					{% endfor %}

					{{ form.non_field_errors }}
				</div>
		    {% endif %}

			<button class="mt-2 p-2 text-md font-bold bg-blue-700 outline-none border-none transition-all duration-300 ease-in-out hover:bg-blue-400 focus:bg-blue-400">Submit</button>
		</form>
	</div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
	<div class="w-1/2 p-6 mx-auto my-6 bg-black text-white rounded-xl">
		<h1 class="mb-6 text-3xl font-semibold">Sign up</h1>

		<form method="post" action=".">
			{% csrf_token %}

			<div class="mb-3">
				<label class="inline-block mb-2">Username</label><br>
				{{ form.username }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Email</label><br>
				{{ form.email }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Password</label><br>
				{{ form.password1 }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Repeat password</label><br>
				{{ form.password2 }}
			</div>

			{% if form.errors or form.non_field_errors %}
				<div class="mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %} 
						{{ field.errors }}
					{% endfor %}

					{{ form.non_field_errors }}
				</div>
		    {% endif %}

			<button class="mt-2 p-2 text-md font-bold bg-blue-700 outline-none border-none transition-all duration-300 ease-in-out hover:bg-blue-400 focus:bg-blue-400">Submit</button>
		</form>
	</div>
{% endblock %}

invitations/templates/invitations/banners.html
{% extends "invitations/base.html" %}

{% block content %}
<div class="relative">
   
</div>
<div class="flex flex-col justify-center max-[768px]:mt-96">
    <div class="flex flex-col justify-center items-center mb-4 md:mb-8 lg:mb-16">
        <h1 class="text-lg sm:text-2xl md:text-3xl lg:text-6xl text-shadow font-bold text-yellow-300 mb-2 md:mb-4">TRAVIS SCOTT</h1>

        <p class="text-shadow-min text-white text-xs sm:text-sm md:text-base lg:text-xl font-bold my-1 md:my-2">
            CENTRAL CEE 🌟 <span class="text-yellow-400">LATTO</span> <sup>USA</sup> 🌟 CENTRAL CEE 🌟 LATTO <sup>USA</sup> 🌟 <span class="text-yellow-400">CENTRAL CEE</span> 🌟 LATTO <sup>USA</sup>
        </p>
        <p class="text-shadow-min text-white text-xs sm:text-sm md:text-base lg:text-xl font-bold my-1 md:my-2">
            CENTRAL CEE 🌟 LATTO <sup>USA</sup> 🌟 <span class="text-yellow-400">CENTRAL CEE</span> 🌟 LATTO <sup>USA</sup>
        </p>

        <p class="text-xs sm:text-sm md:text-base lg:text-xl font-semibold text-white text-shadow-min-min">
            ZIAK 🟌 MAKKO 🟌 MARA 🟌 <span class="text-yellow-400">ZIAK</span> 🟌 MAKKO 🟌 MARA 🟌 ZIAK 🟌 MAKO 🟌 MARA 🟌 ZIAK 🟌 <span class="text-yellow-400">MAKO</span> 🟌 MARA
        </p>
        <p class="text-xs sm:text-sm md:text-base lg:text-xl font-semibold text-white text-shadow-min-min">
            MAKKO 🟌 MARA 🟌 <span class="text-yellow-400">ZIAK</span> 🟌 <span class="text-yellow-400">MAKO</span> 🟌 MARA 🟌 ZIAK 🟌 MAKO 🟌 MARA
        </p>
    </div>

    <div class="flex flex-col justify-center items-center">
        <h1 class="text-lg sm:text-2xl md:text-3xl lg:text-6xl text-shadow font-bold text-yellow-300 mb-2 md:mb-4">KENDRIC LAMAR</h1>

        <p class="text-shadow-min text-white text-xs sm:text-sm md:text-base lg:text-xl font-bold my-1 md:my-2">
            CENTRAL CEE 🌟 <span class="text-yellow-400">LATTO</span> <sup>USA</sup> 🌟 CENTRAL CEE 🌟 LATTO <sup>USA</sup> 🌟 <span class="text-yellow-400">CENTRAL CEE</span> 🌟 LATTO <sup>USA</sup>
        </p>
        <p class="text-shadow-min text-white text-xs sm:text-sm md:text-base lg:text-xl font-bold my-1 md:my-2">
            CENTRAL CEE 🌟 LATTO <sup>USA</sup> 🌟 <span class="text-yellow-400">CENTRAL CEE</span> 🌟 LATTO <sup>USA</sup>
        </p>

        <p class="text-xs sm:text-sm md:text-base lg:text-xl font-semibold text-white text-shadow-min-min">
            ZIAK 🟌 MAKKO 🟌 MARA 🟌 <span class="text-yellow-400">ZIAK</span> 🟌 MAKKO 🟌 MARA 🟌 ZIAK 🟌 MAKO 🟌 MARA 🟌 ZIAK 🟌 <span class="text-yellow-400">MAKO</span> 🟌 MARA
        </p>
        <p class="text-xs sm:text-sm md:text-base lg:text-xl font-semibold text-white text-shadow-min-min">
            MAKKO 🟌 MARA 🟌 <span class="text-yellow-400">ZIAK</span> 🟌 <span class="text-yellow-400">MAKO</span> 🟌 MARA 🟌 ZIAK 🟌 MAKO 🟌 MARA
        </p>
    </div>
</div>
{% endblock %}

invitations/templates/invitations/index.html
{% extends "invitations/base.html" %}

{% block content %}
<div class="min-h-screen flex items-center justify-center">
    <div class=" max-[426px]:w-2/3 max-[786px]:w-1/2 max-[1024px]:w-1/3 text-center p-6">
      <div class="animated-div flex flex-col justify-center items-center max-[426px]:mt-72 max-[769px]:mt-[30rem]">
        <h1 id="header-1" class="header-1 mb-2 text-shadow text-white text-7xl max-[426px]:text-2xl font-bold">TICKETS FOR OAF 24</h1>
        <h1 class="header-2 mb-4 text-shadow text-white text-7xl max-[426px]:text-xl font-bold">AVAILABLE NOW</h1>
        <h3 class="header-3 mb-8 text-shadow text-yellow-400 text-2xl max-[426px]:text-lg font-bold">SAVE THE DATE AND GET YOUR TICKETS NOW</h3>
        <a href="{% url 'invitations:banners' %}" class="text-sm text-black font-bold bg-white rounded-lg py-3 px-5 outline-none border-2 transition-all duration-200 ease-in-out hover:bg-yellow-500 hover:border-black">TICKETS</a>
      </div>
    </div>
</div>
{% endblock %}